import { GlobalNav } from '@/components/shared/GlobalNav';

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-abyss text-foam selection:bg-biolume/30 relative overflow-x-hidden">
      <GlobalNav />

      {/* Decorative background effects */}
      <div className="absolute top-0 left-0 right-0 h-[300px] bg-gradient-to-b from-biolume/5 to-transparent pointer-events-none" />
      
      <div className="max-w-4xl mx-auto px-6 pt-32 pb-20 z-10 relative">
        <h1 className="font-display text-4xl md:text-5xl font-bold tracking-tight text-white mb-4">
          About OceanRoot
        </h1>
        <p className="font-mono text-xs text-biolume tracking-[0.2em] uppercase mb-16">
          System Architecture & Data Sources
        </p>

        <article className="prose prose-invert prose-p:text-foam-dim prose-h2:text-white prose-h2:font-display prose-h2:text-2xl prose-h2:tracking-wide max-w-none">
          <h2>Project Overview</h2>
          <p>
            INCOIS OceanRoot is a high-fidelity, interactive 3D visualization platform designed for oceanographers, researchers, and policymakers. It provides a localized spatial representation of the Indian Ocean, bridging the gap between raw observational data and predictive computational models.
          </p>

          <div className="my-10 h-px w-full bg-gradient-to-r from-thermocline/0 via-thermocline/20 to-thermocline/0" />

          <h2>Data Sources</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6 mb-10">
            <div className="bg-deep-panel/50 border border-thermocline/20 p-6 rounded">
              <h3 className="font-mono text-sm text-biolume uppercase tracking-widest mb-3">Argo Floats</h3>
              <p className="text-sm text-foam-dim m-0">
                Autonomous profiling floats that measure temperature and salinity from the surface down to 2,000 meters. This application streams real-time Argo data to validate oceanic models.
              </p>
            </div>
            <div className="bg-deep-panel/50 border border-thermocline/20 p-6 rounded">
              <h3 className="font-mono text-sm text-instrument-amber uppercase tracking-widest mb-3">Predictive Models</h3>
              <p className="text-sm text-foam-dim m-0">
                Ocean state forecasts generated by INCOIS supercomputers. OceanRoot allows for immediate, visual cross-referencing between these models and real-world observations.
              </p>
            </div>
          </div>

          <h2>System Architecture</h2>
          <p>
            Built using modern web technologies to handle massive datasets efficiently:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4 text-foam-dim">
            <li><strong>Frontend:</strong> Next.js App Router, React, TailwindCSS</li>
            <li><strong>3D Engine:</strong> CesiumJS for geospatial visualization</li>
            <li><strong>Data Visualization:</strong> Custom Three.js GLSL shaders for volumetric ocean rendering and React-Vis for sparkline charting.</li>
          </ul>

          <div className="my-10 h-px w-full bg-gradient-to-r from-thermocline/0 via-thermocline/20 to-thermocline/0" />

          <p className="text-sm text-foam-dim text-center">
            Developed for the Smart India Hackathon (SIH) 2026.
          </p>
        </article>
      </div>
    </main>
  );
}
